import React, {useEffect,useRef,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {ScanLine,Upload,ArrowUpRight,ArrowRight,Check,ChevronRight,ChevronLeft,Search,Database,ChartNoAxesCombined,ShieldCheck,Clock3,Coins,FileJson,Info,AlertCircle,LoaderCircle,Image as ImageIcon,Link2,RefreshCw,CheckCircle2,Layers} from 'lucide-react'
import {comparisonRows,decisionCounts} from './evaluationView.js'
import StudyManual from './studyManual.jsx'
import './style.css'
import './scope.css'
import './theme.css'

const fields={articleType:'Category',baseColour:'Colour',gender:'Catalog audience',season:'Catalog season',usage:'Catalog use'}
const kindLabel={known:'In-catalog shoes',unknown_footwear:'Out-of-catalog shoes',non_footwear:'Non-footwear'}
const pct=v=>v==null?'—':`${(v*100).toFixed(1)}%`
const dec=(v,n=3)=>v==null?'—':Number(v).toFixed(n)
const money=v=>v==null?'Cost unknown':`$${Number(v).toFixed(6)}`
async function api(path,data){const r=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:undefined);if(!(r.headers.get('content-type')||'').includes('application/json'))throw Error('The local Python service returned a page instead of API data. Restart the Python service, then refresh this page.');const json=await r.json();if(!r.ok)throw Error(json.error||'Request failed');return json}
function Icon({icon:IconComponent,...props}){return <IconComponent size={18} strokeWidth={1.65} {...props}/>}
function Metric({label,value,detail,icon}){return <div className="metric"><div className="metric-label">{label}{icon&&<Icon icon={icon}/>}</div><strong>{value}</strong>{detail&&<small>{detail}</small>}</div>}
function Pill({children,tone=''}){return <span className={`pill ${tone}`}>{children}</span>}
function Facts({record}){return <dl className="facts">{Object.entries(fields).map(([key,label])=><div key={key}><dt>{label}</dt><dd>{record[key]||'Not recorded'}</dd></div>)}</dl>}
function download(value,name){const u=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}

function SearchPage({status}){
 const [file,setFile]=useState(null),[preview,setPreview]=useState(''),[data,setData]=useState(null),[result,setResult]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[drag,setDrag]=useState(false),[selected,setSelected]=useState(null),[summary,setSummary]=useState(null),[summarizing,setSummarizing]=useState(false),[llm,setLlm]=useState(true)
 const input=useRef(null);const objectURL=useRef(null)
 useEffect(()=>()=>{if(objectURL.current)URL.revokeObjectURL(objectURL.current)},[])
 function clear(){setResult(null);setSummary(null);setSelected(null);setError('')}
 async function upload(f){if(!f)return;clear();if(!['image/jpeg','image/png','image/webp'].includes(f.type)){setError('Please choose a JPG, PNG or WebP image.');return}if(f.size>8000000){setError('The image must be smaller than 8 MB.');return}if(objectURL.current)URL.revokeObjectURL(objectURL.current);objectURL.current=URL.createObjectURL(f);setPreview(objectURL.current);setFile(f);setData(null);const r=new FileReader();r.onload=()=>setData(r.result.split(',')[1]);r.onerror=()=>setError('Could not read this file. Please choose it again.');r.readAsDataURL(f)}
 async function analyze(){setBusy(true);clear();try{const r=await api('/api/analyze',{image:data,use_llm:llm});setResult(r);setSelected(r.accepted?r.candidates[0]?.record||null:null);setSummary(r.summary)}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function selectCandidate(row){setSelected(row);setSummary(null);setSummarizing(true);setError('');try{const s=await api('/api/candidate-summary',{session_id:result.session_id,product_id:row.id,use_llm:llm});setSummary(s)}catch(e){setError(e.message)}finally{setSummarizing(false)}}
 return <>
 <div className="page-intro search-intro"><div><div className="eyebrow"><span/> SEARCH BY PHOTO</div><h1>See it. <span>Find it.</span></h1><p>Upload a shoe photo to find the same product or similar styles. When the catalog cannot confirm a match, AI can describe what is visible in your photo.</p></div></div>
 {!result&&<div className="search-journey" aria-label="How ShoeLens works"><span><ScanLine size={18}/> Search the catalog</span><ChevronRight size={17}/><span><Layers size={18}/> Compare products</span><ChevronRight size={17}/><span><ImageIcon size={18}/> AI description if uncertain</span></div>}
 <div className={`search-layout ${!result&&!busy?'before-search':''}`}><section className="panel input-panel"><div className="section-title"><h2><span>01</span> Upload your photo</h2><span className="subtle">JPG / PNG / WEBP</span></div>
 <input ref={input} type="file" accept="image/jpeg,image/png,image/webp" aria-label="Upload a product image" onChange={e=>upload(e.target.files[0])} hidden/>
 <button disabled={busy} className={`dropzone ${drag?'dragging':''} ${preview?'with-image':''}`} onClick={()=>input.current.click()} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);if(!busy)upload(e.dataTransfer.files[0])}}>
 {preview?<><img src={preview} alt="Your uploaded image"/><span className="replace"><RefreshCw size={13}/> Change image</span></>:<><div className="upload-icon"><Upload size={26}/></div><strong>Drop a shoe photo here</strong><span>or click to browse your files</span><small>Up to 8 MB · Used for this search only</small></>}
 </button>
 {preview&&<div className="filename"><ImageIcon size={14}/><span>{file?.name}</span><Check size={14}/></div>}
 <label className="toggle-row"><input type="checkbox" checked={llm} onChange={e=>setLlm(e.target.checked)}/><span>Use AI source summaries</span><Pill tone={status?.api_key_configured?'green':'neutral'}>{status?.api_key_configured?'Configured':'Not configured'}</Pill></label>
 {!status?.api_key_configured&&<p className="hint">Without an API key, summaries use catalog templates. Add your OpenRouter key to the project’s .env file, then restart the Python server.</p>}
 <p className="hint visual-auto-note"><Info size={15}/> If a shoe match is uncertain and OpenRouter is configured, a vision model automatically describes visible features. A resized image is sent to OpenRouter and its model provider; image input fees may apply. Product identity remains unconfirmed.</p>
 <button className="primary analyze" disabled={busy||!data} onClick={analyze}>{busy?<><LoaderCircle className="spin" size={18}/> Searching your photo…</>:<>Find this product <ArrowRight size={18}/></>}</button>
 {error&&<div className="error" role="alert"><AlertCircle size={17}/>{error}</div>}
 </section>
 {(busy||result)&&<section className="panel answer-panel" aria-live="polite"><div className="section-title"><h2><span>02</span> {result?.accepted?'Best catalog match':result?.status==='uncertain'?'No confident catalog match':'Search result'}</h2>{result&&<button className="icon-button" aria-label="Download this search result" onClick={()=>download({...result,displayed_summary:summary},'shoelens-result.json')}><FileJson size={18}/></button>}</div>
 {busy?<div className="loading-state"><div className="scan-orbit"><ScanLine size={42}/></div><h3>Searching for your product</h3><p>Comparing catalog products and describing your photo if the match is uncertain.</p><div className="skeleton"/><div className="skeleton short"/></div>:<>
 <div className={`decision ${result.accepted?'pass':'review'}`}><Icon icon={result.accepted?CheckCircle2:AlertCircle}/><div><b>{result.accepted?'Best match found':result.status==='out_of_scope'?'No footwear detected':'No confident catalog match'}</b><p>{result.reason}</p></div></div>
 {result.status==='out_of_scope'?<div className="scope-rejection"><ShieldCheck size={34}/><h3>Try a clear photo of a shoe</h3><p>This image was not classified as footwear, so no shoe matches or summaries are shown. Try a clear photo with the shoe filling most of the frame.</p><button className="secondary" onClick={()=>input.current.click()}><RefreshCw size={14}/> Choose another image</button><small><Clock3 size={13}/>{dec(result.local_seconds,2)}s local category check · No OpenRouter call</small></div>:<>
 {result.status==='uncertain'&&<div className="summary-box visual-observation"><div className="summary-heading"><span><ImageIcon size={17}/> AI description of your photo</span><Pill>Product not identified</Pill></div>{result.visual_summary?.text?<p className="summary-text">{result.visual_summary.text}</p>:<p className="summary-text muted">{result.visual_summary?.warning||'AI description is unavailable. Check the OpenRouter setup or try another photo.'}</p>}{result.visual_summary?.text&&<p className="hint">{result.visual_summary.warning}</p>}{result.visual_summary?.usage&&<small>Visual summary tokens: {result.visual_summary.usage.total_tokens||'Not reported'} · Cost: {result.visual_summary.api_usd==null?'Unknown':money(result.visual_summary.api_usd)}</small>}</div>}
 {selected&&<><div className="chosen-product"><img src={`/image/${selected.id}`} alt="Selected catalog product"/><div><span className="eyebrow">SOURCE #{selected.id}</span><h3>{selected.productDisplayName}</h3><p>{summary?.scope==='user_selected_candidate'?'Selected catalog record · Not verified as the same product':result.accepted?'Top candidate · Please compare the images':'Similar candidate · Match unconfirmed'}</p></div></div>
 <div className="summary-box"><div className="summary-heading"><span><Link2 size={15}/> {result.accepted?'Product details from the catalog':'Details for this possible alternative'}</span>{summary&&<Pill tone="neutral">{summary.mode==='openrouter_grounded'?(summary.cached?'OpenRouter · Cached':'OpenRouter'):'Catalog template'}</Pill>}</div>{summarizing?<p><LoaderCircle size={14} className="spin"/> Preparing the product details…</p>:summary?<>{!result.accepted&&<p className="candidate-disclaimer">These details belong to the selected catalog product. They do not identify the shoe in your photo.</p>}<p className="summary-text">{summary.text}</p>{summary.warning&&<small>{summary.warning}</small>}</>:<div className="candidate-summary-action"><p className="muted">You can inspect the catalog details for this possible alternative.</p><button className="secondary" disabled={summarizing} onClick={()=>selectCandidate(selected)}><Link2 size={14}/> Show product details</button></div>}</div>
 <Facts record={selected}/></>}
 <div className="result-foot"><span><Clock3 size={14}/>{dec(result.local_seconds,2)}s local search</span><span><Coins size={14}/>API {money(result.cost_breakdown?.api_usd)}{result.cost_breakdown?.api_cost_source==='configured_rate_estimate'?' (token-rate estimate)':result.cost_breakdown?.api_cost_source==='provider_reported'?' (provider reported)':''} · Local estimate {money(result.cost_breakdown?.local_estimated_usd)} · Combined estimate {money(result.cost_breakdown?.total_estimated_usd)}{summary?.scope==='user_selected_candidate'&&<> · Selected record API {money(summary.api_usd)}</>}</span></div>
 <details className="evidence-details"><summary>Why this result? <ChevronRight size={14}/></summary><div className="evidence-grid"><span>Top match score<b>{dec(result.score)}</b></span><span>Top-1 / Top-2 gap<b>{dec(result.margin,4)}</b></span><span>Score threshold<b>{dec(result.calibration?.threshold)}</b></span><span>Gap threshold<b>{dec(result.calibration?.margin,4)}</b></span></div><p>The score combines local feature matching (70%) and CLIP similarity (30%). It is not a probability that the product is correct. Thresholds were selected with 40 calibration photos; held-out results are on the Evaluation page.</p>{summary?.usage&&<pre>{JSON.stringify(summary.usage,null,2)}</pre>}</details>
 </>}
 </>}
 </section>}</div>
 {result&&result.status!=='out_of_scope'&&<section className="candidates-section"><div className="section-title"><div><h2><span>03</span> {result.accepted?'Similar products':'Possible alternatives'}</h2><p>{result.accepted?'Other products with a similar appearance in the catalog.':'These products look similar, but none has been confirmed as your uploaded product.'}</p></div><span className="subtle">Select a product to inspect its catalog details</span></div><div className="candidate-grid">{(result.accepted?result.candidates.slice(1):result.candidates).map((h,i)=><article className={`candidate ${selected?.id===h.record.id?'selected':''}`} key={h.record.id}><div className="candidate-photo"><span className="rank">0{i+1}</span><img src={`/image/${h.record.id}`} alt={h.record.productDisplayName}/></div><div className="candidate-content"><div className="candidate-meta">#{h.record.id}<span>Score {dec(h.score)}</span></div><h3>{h.record.productDisplayName}</h3><p>{h.record.articleType} · {h.record.baseColour}</p><button disabled={summarizing} onClick={()=>selectCandidate(h.record)}>View product details <ArrowUpRight size={14}/></button></div></article>)}</div></section>}
 <div className="scope-note"><Info size={16}/><span>A footwear search prototype for a fixed catalog. Summaries do not establish brand, materials, specifications or performance. Audience, season and use are dataset labels.</span></div>
 </>
}

function CatalogPage(){const [data,setData]=useState(null),[q,setQ]=useState(''),[category,setCategory]=useState(''),[page,setPage]=useState(1),[error,setError]=useState(''),[chosen,setChosen]=useState(null);useEffect(()=>{let live=true;const t=setTimeout(()=>{api(`/api/catalog?q=${encodeURIComponent(q)}&category=${encodeURIComponent(category)}&page=${page}`).then(v=>{if(live){setData(v);setError('')}}).catch(e=>{if(live)setError(e.message)})},180);return()=>{live=false;clearTimeout(t)}},[q,category,page]);return <><div className="page-intro compact"><div><div className="eyebrow">CURATED PRODUCT KNOWLEDGE</div><h1>Product catalog</h1><p>Every candidate links to an original record you can inspect.</p></div><Pill>{data?.total.toLocaleString()||'…'} records</Pill></div><div className="toolbar"><div className="search-input"><Search size={17}/><input aria-label="Search by product name or ID" placeholder="Search by name, colour or ID" value={q} onChange={e=>{setQ(e.target.value);setPage(1)}}/></div><select aria-label="Filter by category" value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option value="">All footwear</option>{data?.categories.map(c=><option key={c}>{c}</option>)}</select></div>{error&&<div className="error">{error}</div>}<div className="catalog-grid">{data?.items.map(r=><button className="catalog-item" key={r.id} onClick={()=>setChosen(r)}><img loading="lazy" src={`/image/${r.id}`} alt={r.productDisplayName}/><small>#{r.id} · {r.articleType}</small><h3>{r.productDisplayName}</h3><span>{r.baseColour}<ArrowUpRight size={15}/></span></button>)}</div>{data?.items.length===0&&<div className="panel empty-state"><Search size={35}/><h3>No products found</h3><p>Try a shorter search or a different category.</p></div>}<div className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={16}/> Previous</button><span>Page {page} of {Math.max(1,Math.ceil((data?.total||0)/24))}</span><button disabled={!data||page*24>=data.total} onClick={()=>setPage(p=>p+1)}>Next <ChevronRight size={16}/></button></div>{chosen&&<div className="modal-backdrop" onClick={()=>setChosen(null)}><section className="modal panel" role="dialog" aria-modal="true" aria-label="Catalog record" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setChosen(null)}>Close ×</button><img src={`/image/${chosen.id}`} alt="Catalog product"/><small>DATASET SOURCE #{chosen.id}</small><h2>{chosen.productDisplayName}</h2><Facts record={chosen}/><p className="hint">This is a dataset record, not an identification of any uploaded image.</p></section></div>}</>}

function EvaluationPage(){
 const [report,setReport]=useState(null),[failures,setFailures]=useState([]),[studyCheck,setStudyCheck]=useState(null),[error,setError]=useState('');
 useEffect(()=>{Promise.all([api('/api/evaluation'),api('/api/failures')]).then(([r,f])=>{setReport(r);setFailures(f)}).catch(e=>setError(e.message));api('/api/study/results').then(setStudyCheck).catch(e=>setStudyCheck({pending:true,error:e.message}))},[]);
 if(error)return <div className="error">{error}</div>;
 if(!report)return <div className="loading-state"><LoaderCircle className="spin"/> Loading evaluation results</div>;
 if(report.pending)return <div className="panel empty-state"><ChartNoAxesCombined size={36}/><h2>No evaluation report yet</h2><p>Run python benchmark.py to generate measured results.</p></div>;
 const c=report.results.clip.test,h=report.results.handcrafted?.test,decisions=decisionCounts(c),rows=h?comparisonRows(h,c,c.known_n,c.n):[];
 return <><div className="page-intro compact"><div><div className="eyebrow">MEASURED RESULTS</div><h1>How well does ShoeLens work?</h1><p>40 images set the decision thresholds. These results use 60 separate test images.</p></div><button className="secondary" onClick={()=>download(report,'shoelens-evaluation.json')}><FileJson size={16}/> Download data</button></div>
 <div className="banner"><Info size={18}/><span>These are transformed catalog photos, not independent real-world shoe photos. Results may be optimistic for phone photos.</span></div>
 <section className="panel"><div className="section-title"><h2>Results for 60 test photos</h2><Pill tone="green">CLIP + SIFT</Pill></div><div className="eval-column-chart" role="img" aria-label={`${decisions.correct} correct answers, ${decisions.incorrect} wrong answers, ${decisions.abstained} no confirmed matches`}>{[['correct','Correct answer',decisions.correct],['incorrect','Wrong answer',decisions.incorrect],['abstained','No confirmed match',decisions.abstained]].map(([tone,label,count])=><div className="eval-column" key={tone}><strong>{count}</strong><div className="eval-column-track"><span className={tone} style={{height:`${100*count/c.n}%`}}/></div><small>{label}</small></div>)}</div><p className="hint">A wrong answer is an accepted but incorrect product identity. “No confirmed match” means the system withheld an identity.</p></section>
 {h&&<section className="panel"><div className="section-title"><h2>ShoeLens compared with a model-free baseline</h2><Pill tone="neutral">Same test set</Pill></div><p className="chart-intro">The baseline uses image hashing and colour. ShoeLens uses CLIP and SIFT. Both search the same 2,000 products.</p><div className="eval-table-wrap"><table className="eval-comparison-table"><thead><tr><th>Measure</th><th>Model-free baseline</th><th>ShoeLens</th></tr></thead><tbody>{rows.map(row=><tr key={row.label}><th scope="row"><b>{row.label}</b><small>{row.description}</small></th><td><strong>{row.baselineValue==null?'Not measurable':row.baselineText}</strong><small>{row.baselineCount}</small></td><td><strong>{row.mainText}</strong><small>{row.mainCount}</small></td></tr>)}</tbody></table></div><p className="hint">The baseline accepted no matches, so its accepted-answer accuracy cannot be calculated. Zero wrong accepted answers does not mean it identified products correctly.</p></section>}

 {report.llm_summary&&<section className="panel"><div className="section-title"><h2>OpenRouter summary evaluation</h2><Pill tone={report.llm_summary.complete_accepted_set?'green':'amber'}>{report.llm_summary.complete_accepted_set?'Full accepted set':'Partial run'}</Pill></div><p className="chart-intro">{report.llm_summary.n_evaluated} of {report.llm_summary.n_accepted_expected} accepted test searches were evaluated with {report.llm_summary.model}. The summary uses catalog fields; visual descriptions of uncertain photos are not scored here.</p><div className="eval-table-wrap"><table className="eval-comparison-table"><thead><tr><th>Measure</th><th>Result</th><th>Meaning</th></tr></thead><tbody><tr><th scope="row">Source-supported claims</th><td><strong>{pct(report.llm_summary.source_supported_claim_rate)}</strong><small>{report.llm_summary.emitted_claims} generated claims</small></td><td>Claims agree with the retrieved record; enforced by code.</td></tr><tr><th scope="row">End-to-end claim accuracy</th><td><strong>{pct(report.llm_summary.end_to_end_claim_accuracy)}</strong></td><td>Claims also agree with the query's correct product; wrong retrieval counts as wrong.</td></tr><tr><th scope="row">Validated model responses</th><td><strong>{report.llm_summary.n_openrouter_validated} / {report.llm_summary.n_evaluated}</strong></td><td>{report.llm_summary.n_template_fallbacks} template fallbacks; {report.llm_summary.cache_hits} cache hits.</td></tr><tr><th scope="row">API cost this run</th><td><strong>{money(report.llm_summary.total_api_usd_this_run)}</strong></td><td>{report.llm_summary.provider_reported_cost_calls} provider-reported, {report.llm_summary.token_rate_estimated_cost_calls} token-rate estimates, {report.llm_summary.cost_unknown_calls} unknown.</td></tr><tr><th scope="row">API cost per test image</th><td><strong>{money(report.llm_summary.mean_api_usd_per_test_image_this_run)}</strong></td><td>Shown only for a full accepted-set run with all API costs known; excludes local hardware and electricity.</td></tr></tbody></table></div><p className="hint">A partial run covers the first accepted queries only and is not a representative accuracy estimate. Cached summaries cost $0 in this run; their original generation cost is excluded.</p></section>}


 {report.visual_evaluation&&<section className="panel"><div className="section-title"><h2>OpenRouter visual description evaluation</h2><Pill tone={report.visual_evaluation.human_review_complete===report.visual_evaluation.expected_uncertain_footwear?'green':'amber'}>{report.visual_evaluation.human_review_complete===report.visual_evaluation.expected_uncertain_footwear?'Human review complete':'Human review pending'}</Pill></div><p className="chart-intro">{report.visual_evaluation.n_evaluated} of {report.visual_evaluation.expected_uncertain_footwear} uncertain shoe photos received a visual description. These descriptions do not confirm product identity.</p><div className="eval-table-wrap"><table className="eval-comparison-table"><thead><tr><th>Measure</th><th>Result</th><th>Meaning</th></tr></thead><tbody><tr><th scope="row">Descriptions generated</th><td><strong>{report.visual_evaluation.vision_descriptions_generated} / {report.visual_evaluation.n_evaluated}</strong></td><td>API responses with a usable visible-feature description.</td></tr><tr><th scope="row">Mean API latency</th><td><strong>{dec(report.visual_evaluation.mean_api_seconds,2)}s</strong></td><td>Remote call only; excludes local retrieval and browser interaction.</td></tr><tr><th scope="row">Mean retrieval + visual latency</th><td><strong>{dec(report.visual_evaluation.mean_retrieval_plus_visual_seconds,2)}s</strong></td><td>Local search plus remote description; excludes browser interaction.</td></tr><tr><th scope="row">Provider cost for all descriptions</th><td><strong>{money(report.visual_evaluation.total_api_usd_original_generation)}</strong></td><td>{report.visual_evaluation.original_cost_unknown_calls} calls with unknown cost.</td></tr><tr><th scope="row">Human review completed</th><td><strong>{report.visual_evaluation.human_review_complete} / {report.visual_evaluation.expected_uncertain_footwear}</strong></td><td>Project owner review of the image and generated text.</td></tr><tr><th scope="row">Visible fields judged correct</th><td><strong>{pct(report.visual_evaluation.human_review_field_accuracy)}</strong></td><td>Four fields per image: shoe type, colour, closure, and visible details.</td></tr><tr><th scope="row">Descriptions with unsupported claims</th><td><strong>{report.visual_evaluation.human_review_unsupported_claims}</strong></td><td>Reported in the project owner review.</td></tr></tbody></table></div><p className="hint">Review results are based on the project owner's confirmation for all nine descriptions. These are transformed catalog photos, not independent phone photos.</p></section>}

 {studyCheck?.pending&&<div className="banner"><Info size={17}/><span>{studyCheck.error||'User-study results are unavailable. Restart the local Python service and refresh to load this section.'}</span></div>}
 {studyCheck&&!studyCheck.pending&&<section className="panel"><div className="section-title"><h2>User task study</h2><Pill tone="neutral">{studyCheck.complete_pairs} paired tasks</Pill></div><div className="eval-table-wrap"><table className="eval-comparison-table"><thead><tr><th>Measure</th><th>Manual browsing</th><th>ShoeLens</th></tr></thead><tbody><tr><th scope="row">Complete-task success<small>{studyCheck.complete_pairs} pairs across {studyCheck.participants_recorded} participant codes</small></th><td><strong>{pct(studyCheck.manual_success_rate)}</strong><small>{Math.round(studyCheck.manual_success_rate*studyCheck.complete_pairs)} / {studyCheck.complete_pairs}</small></td><td><strong>{pct(studyCheck.assistant_success_rate)}</strong><small>{Math.round(studyCheck.assistant_success_rate*studyCheck.complete_pairs)} / {studyCheck.complete_pairs}</small></td></tr><tr><th scope="row">Raw completion-time median</th><td><strong>{studyCheck.raw_time_median_seconds?.manual}s</strong></td><td><strong>{studyCheck.raw_time_median_seconds?.assistant}s</strong></td></tr><tr><th scope="row">Season errors</th><td><strong>{studyCheck.field_error_counts?.manual?.season}</strong></td><td><strong>{studyCheck.field_error_counts?.assistant?.season}</strong></td></tr><tr><th scope="row">Paired time reduction<small>Wrong answers count as 180 seconds; median across all pairs</small></th><td>Reference</td><td><strong>{pct(studyCheck.median_paired_time_reduction)}</strong></td></tr><tr><th scope="row">Both-correct time reduction<small>Median of {studyCheck.both_correct_pairs} pairs where both answers were correct</small></th><td>Reference</td><td><strong>{pct(studyCheck.median_both_correct_time_reduction)}</strong></td></tr></tbody></table></div></section>}

 <div className="eval-layout"><section className="panel"><h2>Original versus transformed photos</h2>{[['Original catalog image','original'],['Transformed catalog image','transformed']].map(([name,k])=><div className="bar-row" key={k}><span>{name}</span><div><i style={{width:`${(report.controls.clip[k].known_top1||0)*100}%`}}/></div><b>{pct(report.controls.clip[k].known_top1)}</b></div>)}<p className="hint">Top-1 accuracy on the {c.known_n} in-catalog shoes. Both sets originate from catalog images.</p></section><section className="panel"><h2>Reading these results</h2><p><b>{c.correct_accepted_n} of {c.accepted_n}</b> accepted identities were correct ({pct(c.accepted_identity_accuracy)}). The 95% interval is {c.accuracy_95ci?`${pct(c.accuracy_95ci[0])}–${pct(c.accuracy_95ci[1])}`:'unavailable'}.</p><p><b>{c.accepted_n} of {c.n}</b> test images received a specific answer ({pct(c.coverage)}). Mean local search time was {dec(c.mean_seconds,3)}s on {report.device.toUpperCase()}, excluding model startup and remote API calls.</p><p className="hint">This small, same-source test does not measure real-photo accuracy or human search-time savings.</p></section></div>
 <details className="panel eval-details"><summary>Method, thresholds and additional metrics <ChevronRight size={16}/></summary><div className="eval-detail-content"><p>The match score combines CLIP similarity (30%) and SIFT geometry (70%). It is not a probability. Thresholds were selected on 40 calibration images to target at least 85% accepted accuracy with at least 10 acceptances, then frozen before testing.</p><div className="evidence-grid"><span>Match score threshold<b>{dec(report.results.clip.calibration.threshold,6)}</b></span><span>Top-two gap threshold<b>{dec(report.results.clip.calibration.margin,6)}</b></span><span>Out-of-catalog false acceptance<b>{pct(c.unknown_false_acceptance)}</b></span><span>Mean local search time<b>{dec(c.mean_seconds,3)}s</b></span></div><p className="hint">The model-free baseline has no footwear classifier. These times exclude index creation and API calls.</p></div></details>
 <details className="panel eval-details"><summary>Inspect {failures.length} errors and abstentions <ChevronRight size={16}/></summary><div className="failure-list">{failures.map(r=><details key={r.query_id}><summary><Pill tone={r.accepted?'amber':'neutral'}>{r.accepted?'False acceptance':'Abstained'}</Pill><span>{r.query_id} · {kindLabel[r.kind]}</span><span>Score {dec(r.score)}</span><ChevronRight size={15}/></summary><div className="failure-body"><div><img src={`/query/${r.query_id}`} alt="Query image"/><span>Query / Ground truth {r.expected_id||'Outside catalog'}</span></div><ArrowRight size={20}/><div><img src={`/image/${r.predicted_id}`} alt="Top retrieved candidate"/><span>Top candidate #{r.predicted_id}</span></div><p>Gap {dec(r.margin,4)}. {r.correct?'Correct identity, but below the acceptance threshold.':'Using this candidate as the answer would misidentify the product.'}</p></div></details>)}</div></details>
 <div className="scope-note"><Info size={16}/><span>{report.llm_summary?`OpenRouter summary results cover ${report.llm_summary.n_evaluated} accepted queries${report.llm_summary.complete_accepted_set?' (full accepted set)':' (partial run)'}. Download the report for denominators and limitations.`:'OpenRouter summaries have not been evaluated in a capped run. This page currently measures catalog retrieval only.'}</span></div></>
}

function App(){const [tab,setTab]=useState('search'),[status,setStatus]=useState(null),[error,setError]=useState('');useEffect(()=>{api('/api/status').then(setStatus).catch(e=>setError(e.message))},[]);const nav=[['search','Find a product',ScanLine],['catalog','Product catalog',Database],['evaluation','Evaluation',ChartNoAxesCombined]];return <div className="app-shell"><aside><div className="brand"><span className="brand-icon"><ScanLine size={23}/></span><div>ShoeLens<small>PHOTO PRODUCT SEARCH</small></div></div><div className="nav-label">WORKSPACE</div><nav>{nav.map(([id,name,icon])=><button key={id} aria-label={name} title={name} className={tab===id?'active':''} onClick={()=>setTab(id)}><Icon icon={icon}/>{name}{tab===id&&<span className="nav-dot"/>}</button>)}</nav><div className="sidebar-bottom"><div><span className="online-dot"/> LOCAL WORKSPACE</div><p>PE6201 · Emerging AI Technologies</p><b>Fan Yanxi</b><span>Course project / 2026</span></div></aside><div className="main-shell"><header><div className="breadcrumb">Workspace <ChevronRight size={13}/><b>{nav.find(x=>x[0]===tab)[1]}</b></div><div className="header-right"><Pill tone={status?'green':'amber'}><span className="online-dot"/>{status?'Local service online':'Connecting'}</Pill><span className="avatar">FY</span></div></header><main>{error?<div className="error"><AlertCircle/>{error}. Check that the Python server is running.</div>:!status?<div className="loading-state"><LoaderCircle className="spin"/><p>Connecting to the local model service…</p></div>:tab==='search'?<SearchPage status={status}/>:tab==='catalog'?<CatalogPage/>:<EvaluationPage/>}<footer><span>SHOELENS / Photo product search</span><span>Find the closest match · Explore alternatives</span></footer></main></div></div>}
const studyParams=new URLSearchParams(window.location.search)
createRoot(document.getElementById('root')).render(studyParams.get('study')==='manual'?<StudyManual taskId={studyParams.get('task')||''}/>:<App/>);
